### ISSUE TITLE
Newdiamond won't go back previous selected menu after video play

### ISSUE THREAD

**Issue by minhgi** [henryjfry/repository.thenewdiamond#12]
This would be request for enhancement rather than an issue with the newdiamond/openinfo.  When I click on play in the Diamond info, it will launch TMDBHelper, then auto launch the default player for specific addon, play the video, and the exit video, it would exit back to the skin homescreen rather then the previous newdiamond play menu (the screen where the play button is at).

This problem exist for both Movies and TV Show section.  It mostly a problem in TV Show when you want to go back previous menu to select a different episode after exiting the video.  It's take more time to reopen the newdiamond, search for the TV Show, search for episode, and then play the video. Image if this process need to done for every next episode you want to watch.

**Comment by henryjfry** [comment]
There are two methods for reopening the last screen, with the window stack or with the reopen function.
Both can be enabled in the settings.

So the window stack will store the last window and will pop it from the stack when the video ends.
If that is disabled then the reopen window function will trigger on playback finishing and reopen the last list as a regular plugin call.

I've tested both of the methods pretty extensively with the most recent update i've just pushed and they do work.
However they are somewhat time dependant. So if playback takes more than a certain length of time the "diamond_info_started" variable wont be set.
So that could be a factor?

**Comment by henryjfry** [comment]
Going to close this as the new window stack works, and youve confirmed on reddit/email it works as expected.
Possible future functionality to reopen if playback doesnt start, but ill have to think about how to reliably do that.
