### ISSUE TITLE
Nexus issue

### ISSUE THREAD

**Issue by JayDee696969** [henryjfry/repository.thenewdiamond#13]
Hello, just letting you know, extendedinfo is not working on Android OS in the latest Kodi Nexus. It seems to be working fine on Windows and Linux, but does not open he info if on Android. 
To reproduce: Open Diamond Extended Info, Click ALL Movies, or All TV, then click on one of the titles. It does not advance to the Info dialog, just stays "Working". You can press the context on the title and click Play to bring up the TMDBH players.

**Comment by JayDee696969** [comment]
Has something to do with the PIL. ImportError: cannot import name'_imaging' from resources.PIL

**Comment by henryjfry** [comment]
PIL from within the addon should only be called if it isnt available from within Kodi. And it should be available in kodi. 
Before PIL issues havent been strictly speaking diamond related.

From what I recall last time the person had installed the diamond PIL module which isnt actually required.

I know its been a while, im hoping its resolved in the meantime.
But let me know if its still an issue, i just pushed a big update too.

**Comment by henryjfry** [comment]
So i tried installing Nexus on Android and trying Diamondinfo and I got the PIL error too.
So im pretty sure my workaround install of:

/.kodi/addons/script.extendedinfo/resources/PIL/
/.kodi/addons/script.extendedinfo/resources/PIL2/

Isnt working on Nexus because of a different version of Python?

In my PIL there is:

/.kodi/addons/script.extendedinfo/resources/PIL/_imaging.cpython-37m-arm-linux-gnueabihf.so
/.kodi/addons/script.extendedinfo/resources/PIL/_imagingcms.cpython-37m-arm-linux-gnueabihf.so
/.kodi/addons/script.extendedinfo/resources/PIL/_imagingft.cpython-37m-arm-linux-gnueabihf.so
/.kodi/addons/script.extendedinfo/resources/PIL/_imagingmath.cpython-37m-arm-linux-gnueabihf.so
/.kodi/addons/script.extendedinfo/resources/PIL/_imagingmorph.cpython-37m-arm-linux-gnueabihf.so

While the Kodi nexus apk i just downloaded is going to be python 3.9?

So i think dont use nexus for now.

**Comment by JayDee696969** [comment]
Kodi 20 is now final, so hopefully we could figure this out. Looks like Kodi 20 final uses python 3.8.

**Comment by henryjfry** [comment]
Ahh could be a version issue




from PIL.Image import core as _imaging

**Comment by JayDee696969** [comment]
Ill give it a shot a little later

**Comment by henryjfry** [comment]
It's an easy fix actually.

You just need to add script.module.pil as a dependency in addon.xml

**Comment by JayDee696969** [comment]
Beautiful! Thank you!!

**Comment by henryjfry** [comment]
Updated to include dependency
