### ISSUE TITLE
Weird Titan MOD skin issue connected with Extended Info-Diamond_MOD

### ISSUE THREAD

**Issue by cg00001** [henryjfry/repository.thenewdiamond#20]
I notified the dev of Titan MOD skin first, since that issue is quite old, maybe there's nothing you can do, thought you should know anyway.
https://forum.kodi.tv/showthread.php?tid=330749&pid=3165797#pid3165797

**Comment by henryjfry** [comment]
Based on the description that's some dependency on an extendedinfo/diamondinfo plugin path.
I'm guessing whatever functionality the plugin path fulfills would need to be completed by some other addon/version of extendedinfo.

The likely fix is to use a new version of extendedinfo? But I started fixing this one because the Kodi 19 one was terrible.
So I think if you use titan mod you'll just have to put up with this?

**Comment by cg00001** [comment]
> Based on the description that's some dependency on an extendedinfo/diamondinfo plugin path. I'm guessing whatever functionality the plugin path fulfills would need to be completed by some other addon/version of extendedinfo.
> 
> The likely fix is to use a new version of extendedinfo? But I started fixing this one because the Kodi 19 one was terrible. So I think if you use titan mod you'll just have to put up with this?
> 
> Is titan mod still developed? Or is it dead now?

I was testing the new Titan MOD version that was out a few days ago, that issue was there for the previous Titan MODs though.
It doesn't bother me at all, I used Extended Info-Diamond_MOD in the past disabled on start of my 3 skin build with a shortcut to enable it on demand. That's where it was problematic. I did that to avoid the other Extended info being installed -same name, so it got in the way.
Keeping Extended Info-Diamond_MOD installed from the start presents no issue, and I use 1 less shortcut, lol.

**Comment by henryjfry** [comment]
Can you replicate the error and post the section from the log?

Im just curious exactly what titan mod is doing and what the extendedinfo function its calling is?

Havng done a quick search in the code I think the correct fix would be to use the equivalent call in embuary helper? Which i think is the backup where extendedinfo is not explicitly required?
But it would depend.

I fixed a bunch of stuff thats been annoying me in the latest version of my extendedinfo, just fyi.

**Comment by cg00001** [comment]
> Can you replicate the error and post the section from the log?
> 
> Im just curious exactly what titan mod is doing and what the extendedinfo function its calling is?
> 
> Havng done a quick search in the code I think the correct fix would be to use the equivalent call in embuary helper? Which i think is the backup where extendedinfo is not explicitly required? But it would depend.
> 
> I fixed a bunch of stuff thats been annoying me in the latest version of my extendedinfo, just fyi.

[kodi.log](https://github.com/henryjfry/repository.thenewdiamond/files/12605003/kodi.log)
These may (or may not) help:
2041: Extended info disabled
2611: Possible start of error implicating Extended info and Set thumbnail
3133: Extended info enabled
3704: Successful execution of Set thumbnail

**Comment by henryjfry** [comment]
Ok so "script.skin.helper.service" has a specific dependency on "script.extendedinfo" and that particualr part of the skin is triggering "skinshortcuts.py" in skinhelper service which has the following bit of code at the top:

```
EXTINFO_CREDS = False
if getCondVisibility("System.Hasaddon(script.extendedinfo)"):
    exinfoaddon = xbmcaddon.Addon(id="script.extendedinfo")
    if exinfoaddon.getSetting("tmdb_username") and exinfoaddon.getSetting("tmdb_password"):
        EXTINFO_CREDS = True
    del exinfoaddon
```

**Comment by henryjfry** [comment]
Im curious what the whole extendedinfo/diamondinfo thing youve got going on is?

I used to use titan mod myself and at that time I had two versions of extendedinfo installed. So the skin has a lot of integration with it doesnt it?

So is it possible or would you ever want to run the skin without extended info?
(thats one query I have)

If not, is there an "official" version of extendedinfo you are running? In addition to my version?

When I took over diamondinfo/extendedinfo i preserved and am still preserving two identical versions of the addon so that if i wanted to have the official one and also diamondinfo, that was possible.

So im trying to figure out your use case, why you need to enable and disable extendedinfo. 
And by extension try and figure out whatever the fix would be for titan/skin helper service.  Is there a big dependency on "the official" extendedinfo and this isnt a bug at all?
And you are just using it in a weird and unsupported way?

**Comment by cg00001** [comment]
> Im curious what the whole extendedinfo/diamondinfo thing youve got going on is?
> 
> I used to use titan mod myself and at that time I had two versions of extendedinfo installed. So the skin has a lot of integration with it doesnt it?
> 
> So is it possible or would you ever want to run the skin without extended info? (thats one query I have)
> 
> If not, is there an "official" version of extendedinfo you are running? In addition to my version?
> 
> When I took over diamondinfo/extendedinfo i preserved and am still preserving two identical versions of the addon so that if i wanted to have the official one and also diamondinfo, that was possible.
> 
> So im trying to figure out your use case, why you need to enable and disable extendedinfo. And by extension try and figure out whatever the fix would be for titan/skin helper service. Is there a big dependency on "the official" extendedinfo and this isnt a bug at all? And you are just using it in a weird and unsupported way?

I like your Extended info, and since I found out all the fuss happens to me when I disable it, I simply don't disable it, lol.

I don't use other Extended Infos, I believe what I'm using -updated just after sending the log- is the current from your repo.
![eidm](https://github.com/henryjfry/repository.thenewdiamond/assets/38960370/e3e7e41a-1fba-42de-88a2-4512f6af990a)
For me, this issue is solved.

**Comment by henryjfry** [comment]
Yeah that's the very latest version
I fixed a lot of stuff with the window stack.
